// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-cIp3FFoYyTC6ULewMqHI445i8qlUDA',
    appId: '1:1041061329780:android:acebe0cf529272768f4a21',
    messagingSenderId: '1041061329780',
    projectId: 'flutter-chat-app-24ec3',
    storageBucket: 'flutter-chat-app-24ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjeaU733nLEfjS7LBTa7-pVlrQIdxLjOU',
    appId: '1:1041061329780:ios:466a54ecd58aad4d8f4a21',
    messagingSenderId: '1041061329780',
    projectId: 'flutter-chat-app-24ec3',
    storageBucket: 'flutter-chat-app-24ec3.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Bk9uMjHvQSAiAMkPtwAzXH2Jq3XZo0M',
    appId: '1:1041061329780:web:3555471a1cc4c3c88f4a21',
    messagingSenderId: '1041061329780',
    projectId: 'flutter-chat-app-24ec3',
    authDomain: 'flutter-chat-app-24ec3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-24ec3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjeaU733nLEfjS7LBTa7-pVlrQIdxLjOU',
    appId: '1:1041061329780:ios:466a54ecd58aad4d8f4a21',
    messagingSenderId: '1041061329780',
    projectId: 'flutter-chat-app-24ec3',
    storageBucket: 'flutter-chat-app-24ec3.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Bk9uMjHvQSAiAMkPtwAzXH2Jq3XZo0M',
    appId: '1:1041061329780:web:c20a72700f04e7378f4a21',
    messagingSenderId: '1041061329780',
    projectId: 'flutter-chat-app-24ec3',
    authDomain: 'flutter-chat-app-24ec3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-24ec3.firebasestorage.app',
  );

}